### PR TITLE
feat: recognizer builder for avoiding waste time in get_token

### PR DESCRIPTION
**Pull request by giangndm**
This PR introduces RecognizerBuilder for pre-creating tokens.

Why I need this: When I used STT in a voice assistant service, sometimes get_token took a lot of time to connect, and because it is synchronous, it blocked the entire Tokio worker.

### CODE REVIEW

**Comment by adambezecny** [comment]
hi,

thank you for the PR. Give me some time to review and come back to you. I hope to do it next week.

**Comment by adambezecny** [comment]
hi, I just gave it first look and here is my initial feedback:

- first of all I am not actively working with this code base for quiet a long time so pardon me if I will be little slow and off the track :)
-   in general I am pretty confused with this PR
- you say **get_token** takes long time to connect thus blocking your async worker. In my understanding **get_token** is not connecting at all which is the reason why it is implemented as synchronous function, not async one. this is simply parsing google credentials string (with json data) should be fast with no point doing it in async way. reading creds from file could benefit from async but you can do it outside of library in your code and just provide string to library
- i really don't like this **RecognizerBuilder**.  What it is actually building? To me this seems just like mere wrapper around token, why do we need this? 
- changes in **Recognizer**:  you basically moved original methods into new ones (*token, e.g. **create_synchronous_recognizer**, **create_streaming_recognizer_with_token**). I am fighting to see the benefit here.

Maybe I just missed the point and it needs additional clarification but at this time I am pretty confused :)

Btw. we are using **gouth** in version **0.2.1** right now, there is already version **goauth = "0.16.0"** available (https://crates.io/crates/goauth). It seems they have some async api available (see https://durch.github.io/rust-goauth/goauth/fn.get_token.html versus https://durch.github.io/rust-goauth/goauth/fn.get_token_blocking.html). Maybe this would be more straightforward way to remove any blocking code? But I would really like to understand how exactly you are loading the credentials right now and what/where is blocking. Some example would be great.

**Comment by adambezecny** [comment]
hi,

please provide the answer for initial PR review so that we can continue. If there will be no further activity on this PR I will close it.

thx

**Comment by giangndm** [comment]
@adambezecny sorry for missing you reply. 

As I checked the goauth source code, `get_token` actually makes an http post each time we call `get_token`.

https://github.com/durch/rust-goauth/blob/25fa9f74b321519088261fd571d5a1fa24e1836b/src/lib.rs#L123-L150
```rust
pub fn get_token(jwt: &Jwt<JwtClaims>, credentials: &Credentials) -> Result<Token> {
    get_token_with_client(jwt, credentials)
}


pub fn get_token_with_client(jwt: &Jwt<JwtClaims>, credentials: &Credentials) -> Result<Token> {
    let jwt_body = jwt.finalize()?;


    get_token_with_client_and_body(jwt_body, credentials)
}


pub(crate) fn get_token_with_client_and_body(
    jwt_body: String,
    credentials: &Credentials,
) -> Result<Token> {
    let request_body = form_body(&jwt_body);


    let response = attohttpc::post(credentials.token_uri())
        .form(&request_body)?
        .send()?;


    if response.status().is_success() {
        let token = response.json::<Token>()?;
        Ok(token)
    } else {
        let token_err = response.json::<auth::TokenErr>()?;
        Err(GoErr::from(token_err))
    }
}
```

**Comment by adambezecny** [comment]
ok, so would upgrading the latest version of library help? it seems it has some async version of _get_token_. I want to prevent doing any extensive changes that would try to solve something that is already solved by library. can you check?

**Comment by adambezecny** [comment]
closing due to no activity. feel free reopen if when ready to continue in discussion.

**Pull request closed without merging**
