### PR TITLE
Add latest_long and latest_short to Recognition config model enum

### PR DESCRIPTION
**Pull request by vemarun**

### CODE REVIEW

**Comment by adambezecny** [comment]
hi,

thank you for your contribution. Could you please elaborate little bit on why this is needed/what it is solving? Maybe some example code utilising it would be great.

**Comment by slesinger** [comment]
Hi Adam, for some languages which do not have enhanced model, we offer our business colleagues to evaluate standard model for testing. This PR will unlock to test with these two new models types. They are offered by the Google API hence it should be reflected here, too. Thank you.

**Comment by adambezecny** [comment]
Hi Honzo🙂 ill have a look, give me some time please. Thx

**Comment by adambezecny** [comment]
hi Honzo,

two notes:

- according to google doc also **v1p1beta1** supports these models. Can you please extend **v1p1beta1.rs** as well please to keep it consistent? 
- according to doc it seems other models are available as well (e.g. **medical_conversation**, **medical_dictation**). To keep the library as generic as possible I think it would make sense to include these as well. Any suggestions here?

regards,

Adam

https://cloud.google.com/speech-to-text/docs/reference/rest/v1/RecognitionConfig
https://cloud.google.com/speech-to-text/docs/reference/rest/v1p1beta1/RecognitionConfig

**Comment by vemarun** [comment]
Hi Adam,
Pls review changes, i don't have made any changes to v1p1beta1 as i can see it inherits from v1. Please correct me if i am wrong.
Thanks.

```
use super::v1::{
    default_audio_channel_count, default_enable_automatic_punctuation,
    default_enable_separate_recognition_per_channel, default_enable_word_time_offsets,
    default_encoding, default_language_code, default_max_alternatives, default_model,
    default_profanity_filter, AudioEncoding, RecognitionConfigModel, RecognitionMetadata,
    SpeakerDiarizationConfig,
};
```

**Comment by adambezecny** [comment]
you are right, I did not look properly, long time I haven't touched this code :-) Looks good now, give me some time to prepare new version.

**Comment by adambezecny** [comment]
Hi,

new version has been prepared, see https://github.com/jabber-tools/google-cognitive-apis/releases/tag/0.2.2 

enjoy! :)

Adam

**Pull request merged**
